### ISSUE TITLE
Support keep-alive

### ISSUE THREAD

**Issue by duncan-bayne** [mikecmpbll/betfair#5]
Support [HTTP keep-alive](https://en.wikipedia.org/wiki/HTTP_persistent_connection) for speedier requests.

(I'll be addressing this with a PR soon ...)

**Comment by mikecmpbll** [comment]
hi @duncan-bayne. is this the same Keep Alive as described here https://api.developer.betfair.com/services/webapps/docs/display/1smk3cen4v3lu3yomq5qye0ni/Keep+Alive ? if so, that appears to be a session extender implemented by Betfair rather than the keep-alive HTTP header that you linked to. (for what it's worth, this looks like it might be a useful addition too.)

If it's the HTTP keep-alive that you're referring to, do you have any links that show that Betfair recommend a persistent connection? (makes sense, but just want to be sure!)

**Comment by mikecmpbll** [comment]
nvm w.r.t. my last question, found something:

> We recommend that Connection: keep-alive header is set for all requests to guarantee a persistent connection and therefore reducing latency.

https://api.developer.betfair.com/services/webapps/docs/display/1smk3cen4v3lu3yomq5qye0ni/Optimizing+API+Application+Performance

look forward to the PR!

**Comment by duncan-bayne** [comment]
Okay, so I might have been a little optimistic in describing the PR as coming 'soon' :)

It turns out [HTTPI doesn't support keep-alive](https://github.com/savonrb/httpi/issues/41), at least not yet.

I've modified my app to use [Faraday](https://github.com/lostisland/faraday) with [net-http-persistent](https://github.com/drbrain/net-http-persistent).  That works really nicely; connections are kept open, and overall processing time drops _way_ down.

So ... would you be open to the idea of a PR that switches this library over to using Faraday?  It'd be a pretty major change.

**Comment by mikecmpbll** [comment]
crap.

hmm, Faraday isn't desperately different in design to HTTPI, in that it supports multiple adapters, so in theory it should be possible to write a net-http-persistent adapter for HTTPI or modify the net-http adapter or something.

i'll take a look this evening!

**Comment by mikecmpbll** [comment]
not forgotten about this, just been super busy. hope to look at it in the next week or so :kissing_heart:

**Comment by mikecmpbll** [comment]
riight so, finally got around to looking at this. because we're using HTTPI, kind of the advantage of it is you can use whichever underlying client library you want (whether we want to continue this way is another question).

there's [already](https://github.com/savonrb/httpi/blob/master/lib/httpi/adapter/net_http_persistent.rb) a net-http-persistent adapter for HTTPI, and at least one other adapter (httpclient) which supports keep-alive, so in my view we don't need to make any changes except to the README to make it clear that it's recommended that you use a keep-alive connection. to use net_http_persistent, simply:

``` ruby
require 'betfair'
HTTPI.adapter = :net_http_persistent # because it's lower precedence than net-http
```

as far as i can tell, httpclient automatically caches connections where the server supports it, so simply using that adapter should be enough to use a persistent connection. because the httpclient has the highest precedence of the adapters, simply having it installed and in your load path is enough to use that adapter for betfair.

i'll update the readme now.
